# fly.toml app configuration file generated for solarnest-summer-bush-1694 on 2025-03-31T21:44:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'solarnest-summer-bush-1694'
primary_region = '1hr'

[build]

[[services]]
  protocol     = "tcp"
  internal_port = 8080     # your Gin HTTP server binds here

  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 1883
  protcol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 1883
    handlers = [ ]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
